var_sssd_ldap_tls_ca_dir: !!str /etc/openldap/cacerts
var_sshd_set_keepalive: !!str 0
sshd_idle_timeout_value: !!str 600
sshd_approved_macs: !!str hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
inactivity_timeout_value: !!str 900
rsyslog_remote_loghost_address: !!str logcollector
sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: !!str 1
sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
var_selinux_policy_name: !!str targeted
var_selinux_state: !!str enforcing
var_account_disable_post_pw_expiration: !!str 0
var_accounts_minimum_age_login_defs: !!str 1
var_accounts_maximum_age_login_defs: !!str 60
var_accounts_passwords_pam_faillock_unlock_time: !!str never
var_password_pam_unix_remember: !!str 5
var_accounts_passwords_pam_faillock_fail_interval: !!str 900
var_accounts_passwords_pam_faillock_deny: !!str 3
var_password_pam_minlen: !!str 15
var_password_pam_maxclassrepeat: !!str 4
var_password_pam_maxrepeat: !!str 3
var_password_pam_dcredit: !!str -1
var_password_pam_minclass: !!str 4
var_password_pam_difok: !!str 8
var_password_pam_ocredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_ucredit: !!str -1
var_password_pam_retry: !!str 3
login_banner_text: !!str (^You[\s\n]+are[\s\n]+accessing[\s\n]+a[\s\n]+U.S.[\s\n]+Government[\s\n]+\(USG\)[\s\n]+Information[\s\n]+System[\s\n]+\(IS\)[\s\n]+that[\s\n]+is[\s\n]+provided[\s\n]+for[\s\n]+USG-authorized[\s\n]+use[\s\n]+only.[\s\n]*By[\s\n]+using[\s\n]+this[\s\n]+IS[\s\n]+\(which[\s\n]+includes[\s\n]+any[\s\n]+device[\s\n]+attached[\s\n]+to[\s\n]+this[\s\n]+IS\),[\s\n]+you[\s\n]+consent[\s\n]+to[\s\n]+the[\s\n]+following[\s\n]+conditions\:(\\n)*(\n)*-[\s\n]*The[\s\n]+USG[\s\n]+routinely[\s\n]+intercepts[\s\n]+and[\s\n]+monitors[\s\n]+communications[\s\n]+on[\s\n]+this[\s\n]+IS[\s\n]+for[\s\n]+purposes[\s\n]+including,[\s\n]+but[\s\n]+not[\s\n]+limited[\s\n]+to,[\s\n]+penetration[\s\n]+testing,[\s\n]+COMSEC[\s\n]+monitoring,[\s\n]+network[\s\n]+operations[\s\n]+and[\s\n]+defense,[\s\n]+personnel[\s\n]+misconduct[\s\n]+\(PM\),[\s\n]+law[\s\n]+enforcement[\s\n]+\(LE\),[\s\n]+and[\s\n]+counterintelligence[\s\n]+\(CI\)[\s\n]+investigations.(\\n)*(\n)*-[\s\n]*At[\s\n]+any[\s\n]+time,[\s\n]+the[\s\n]+USG[\s\n]+may[\s\n]+inspect[\s\n]+and[\s\n]+seize[\s\n]+data[\s\n]+stored[\s\n]+on[\s\n]+this[\s\n]+IS.(\\n)*(\n)*-[\s\n]*Communications[\s\n]+using,[\s\n]+or[\s\n]+data[\s\n]+stored[\s\n]+on,[\s\n]+this[\s\n]+IS[\s\n]+are[\s\n]+not[\s\n]+private,[\s\n]+are[\s\n]+subject[\s\n]+to[\s\n]+routine[\s\n]+monitoring,[\s\n]+interception,[\s\n]+and[\s\n]+search,[\s\n]+and[\s\n]+may[\s\n]+be[\s\n]+disclosed[\s\n]+or[\s\n]+used[\s\n]+for[\s\n]+any[\s\n]+USG-authorized[\s\n]+purpose.(\\n)*(\n)*-[\s\n]*This[\s\n]+IS[\s\n]+includes[\s\n]+security[\s\n]+measures[\s\n]+\(e.g.,[\s\n]+authentication[\s\n]+and[\s\n]+access[\s\n]+controls\)[\s\n]+to[\s\n]+protect[\s\n]+USG[\s\n]+interests--not[\s\n]+for[\s\n]+your[\s\n]+personal[\s\n]+benefit[\s\n]+or[\s\n]+privacy.(\\n)*(\n)*-[\s\n]*Notwithstanding[\s\n]+the[\s\n]+above,[\s\n]+using[\s\n]+this[\s\n]+IS[\s\n]+does[\s\n]+not[\s\n]+constitute[\s\n]+consent[\s\n]+to[\s\n]+PM,[\s\n]+LE[\s\n]+or[\s\n]+CI[\s\n]+investigative[\s\n]+searching[\s\n]+or[\s\n]+monitoring[\s\n]+of[\s\n]+the[\s\n]+content[\s\n]+of[\s\n]+privileged[\s\n]+communications,[\s\n]+or[\s\n]+work[\s\n]+product,[\s\n]+related[\s\n]+to[\s\n]+personal[\s\n]+representation[\s\n]+or[\s\n]+services[\s\n]+by[\s\n]+attorneys,[\s\n]+psychotherapists,[\s\n]+or[\s\n]+clergy,[\s\n]+and[\s\n]+their[\s\n]+assistants.[\s\n]+Such[\s\n]+communications[\s\n]+and[\s\n]+work[\s\n]+product[\s\n]+are[\s\n]+private[\s\n]+and[\s\n]+confidential.[\s\n]+See[\s\n]+User[\s\n]+Agreement[\s\n]+for[\s\n]+details.$|^I\'ve[\s\n]+read[\s\n]+\&[\s\n]+consent[\s\n]+to[\s\n]+terms[\s\n]+in[\s\n]+IS[\s\n]+user[\s\n]+agreem\'t$)
var_accounts_user_umask: !!str 077
var_accounts_tmout: !!str 600
var_accounts_fail_delay: !!str 4
var_accounts_max_concurrent_login_sessions: !!str 10
var_auditd_space_left: !!str 100
var_auditd_action_mail_acct: !!str root
var_auditd_space_left_action: !!str email
var_removable_partition: !!str /dev/cdrom
