---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/docker/tasks/main.yml

- name: check if selinux is enabled
  command: sestatus
  register: sestatus
  changed_when: false

- name: run operating system specific commands
  include: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: be sure the /etc/systemd/system/docker.service.d folder exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: be sure the docker loads environment variables from /etc/environment
  copy:
    src: environment.conf
    dest: /etc/systemd/system/docker.service.d/environment.conf

- name: run the docker cis benchmark
  include: cis-benchmark.yml
